name: Upload JAR as Release Asset

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_tag
        run: echo "LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)" >> $GITHUB_ENV

      - name: Determine new tag
        id: new_tag
        run: |
          # Generate a unique tag based on date and time
          DATE_TAG=$(date +'%Y%m%d%H%M%S')
          echo "NEW_TAG=v${DATE_TAG}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR File
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/artifacts/Tic_Tac_Toe_jar/Tic-Tac-Toe.jar
          asset_name: Tic-Tac-Toe.jar
          asset_content_type: application/java-archive
